// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("SomeTest", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("SomeTest", async function () {
    await driver.get("http://localhost:5173/");
    await driver.manage().window().setRect({ width: 1680, height: 940 });
    await driver.findElement(By.css(".e2e-input")).click();
    await driver
      .findElement(By.css(".e2e-input"))
      .sendKeys("This is recorded :)");
  });
});
